model:
  type: fully-connected
  input_dim: 2 # Ideally, these follow automatically from the data
  output_dim: 1 # Ideally, these follow automatically from the data
  layers:
    - type: dense
      nodes: 8
      activation: relu
      dropout: 0.1
    - type: dense
      nodes: 8
      activation: relu
      dropout: 0.1
    - type: dense
      nodes: output
      activation: linear
      dropout: -1
fitpars:
  epochs: 10
loss:
  type: mse
optimiser:
  adam:
    lr: 0.01
data:
  checkerboard:
    n: 10000
    k: 2



