model:
  type: fully-connected # -> Generalize to feed forward and include convnet layers
  input_dim: 10 # Ideally, these follow automatically from the data
  output_dim: 10 # Ideally, these follow automatically from the data
  layers:
    - type: dense
      nodes: 32
      activation: relu
      dropout: -1
    - type: dense
      nodes: 32
      activation: relu
      dropout: -1
    - type: dense
      nodes: output
      activation: linear
      dropout: -1
fitpars:
  epochs: 100
  batch_size: 64
loss:
  type: mse
optimiser:
  adam:
    lr: 0.02
data:
  normal_mirror:
    n: 100000
    k: 10
    seed: 42





